analyze:
  position: # left, up, right, bottom
    - 974
    - 5
    - 993
    - 21
  method: static_compare
  method_param:
    compare_image_fp: "image/in_game.png"

observation:
  my_turn:
    position: # left, up, right, bottom
      - 477
      - 158
      - 523
      - 174

    method: static_compare
    status:
      - yes
    method_param:
      compare_image_fp:
        - "image/in_game_my_turn.png"

  host:
    position: # left, up, right, bottom
      - 47
      - 439
      - 83
      - 455
    method: static_compare
    status:
      - yes
      - no
    method_param:
      compare_image_fp:
        - "image/in_game_hosting.png"
        - "image/in_game_not_hosting.png"

  wind:
    position:
      - 461
      - 17
      - 537
      - 48
    method: onnx_rec
    method_param:
      preprocess: CTC
      postprocess: CTC
      onnx_model: "model/wind_1_rec_en_number_lite/wind_1_rec_en_number_lite.onnx"
      character_dict: "model/wind_1_rec_en_number_lite/wind_dict.txt"

  left_wind:
    position:
      - 466
      - 31
      - 467
      - 32
    channel: # 指定图像通道
      - 0
    method: equal
    status:
      - yes
    method_param:
      compare_value:
        - - 245

  angle:
    position:
      - 29
      - 555
      - 73
      - 576
    method: onnx_rec
    method_param:
      preprocess: CTC
      postprocess: CTC
      onnx_model: "model/angle_1_rec_en_number_lite/angle_1_rec_en_number_lite.onnx"
      character_dict: "model/angle_1_rec_en_number_lite/angle_dict.txt"


action:
  cancel_host:
    method: left_click
    param:
      - 500
      - 240
