analyze:
  position:  # left, up, right, bottom
    - 776
    - 12
    - 822
    - 36
  method: static_compare
  method_param:
    compare_image_fp: "image/in_room.png"

observation:
  ready:
    position:  # left, up, right, bottom
      - 929
      - 514
      - 983
      - 529
    method: static_compare
    status:
      - no
      - yes
    method_param:
      compare_image_fp:
        - "image/in_room_ready.png"
        - "image/in_room_start.png"

  bag_available:
    position:
      - 688
      - 550
      - 719
      - 579
    method: static_compare
    status:
      - yes
      - no
    method_param:
      compare_image_fp:
        - "image/in_room_bag_available.png"
        - "image/in_room_bag_not_available.png"

action:
  start_game:
    method: left_click
    param:
      - 940
      - 470

  open_bag:
    method: left_click
    param:
      - 703
      - 564
